// styles/ControlButtonsStyles.js
import { StyleSheet } from 'react-native';

export const Styles = StyleSheet.create({
        settingsButton: {
          position: 'absolute',
          top: 40,
          left: 20,
          zIndex: 10,
          backgroundColor: 'rgba(0, 0, 0, 0.5)',
          borderRadius: 20,
          padding: 8,
        },
        textLeft: {
          left: 10, // Move text to the left when "ON"
        },
        textRight: {
          right: 6, // Move text to the right when "OFF"
        },
        toggleButton: {
          top: -660,
          right: -245,
          width: 60,
          height: 30,
          borderRadius: 30,
          padding: 4,
          flexDirection: 'row',
          alignItems: 'center',
          justifyContent: 'space-between',
          position: 'relative',
        },
        slider: {
          width: 26,
          height: 26,
          borderRadius: 13,
          borderWidth: 2,
          borderColor: '#34C759',
          backgroundColor: '#FFF',
          position: 'absolute',
          top: 2,
          left: 2,
        },
        toggleButtonText: {
          color: '#FFF',
          fontWeight: '600',
          fontSize: 12,
          position: 'absolute',
          // right: 10,
          // marginLeft: 8,
        },
      
        buttonsContainer: {
          position: 'absolute',
          bottom: 30,
          left: 0,
          right: 0,
          flexDirection: 'row',
          justifyContent: 'space-between',
          alignItems: 'center',
          paddingHorizontal: 20,
        },
        centerButtonContainer: {
          flex: 1,
          alignItems: 'center',
        },
        languageToggle: {
          backgroundColor: '#007AFF',
          padding: 12,
          borderRadius: 25,
          flexDirection: 'row',
          alignItems: 'center',
          gap: 8,
        },
        toggleText: {
          color: '#FFF',
          fontSize: 14,
          fontWeight: '600',
        },
        galleryButton: {
          backgroundColor: '#34C759',
          padding: 12,
          borderRadius: 25,
        },
        // previousButton: {
        //   position: 'absolute',
        //   left: 20,
        //   top: 20,
        //   backgroundColor: '#007AFF',
        //   borderRadius: 25,
        //   padding: 12,
        //   flexDirection: 'row',
        //   alignItems: 'center',
        //   zIndex: 10,
        //   shadowColor: '#000',
        //   shadowOffset: { width: 0, height: 2 },
        //   shadowOpacity: 0.25,
        //   shadowRadius: 4,
        //   elevation: 5,
        // },
        translationStatus: {
          flexDirection: 'row',
          alignItems: 'center',
          justifyContent: 'center',
          padding: 8,
          backgroundColor: '#F8F9FA',
          borderRadius: 8,
          marginBottom: 10,
        },
        translationStatusText: {
          marginLeft: 8,
          color: '#666',
          fontSize: 14,
        },
        space: {
          flex: 1,
          justifyContent: 'space-evenly'
        },
        container: {
          flex: 1,
          // backgroundColor: '#e6d2fd',
          // backgroundColor: '#07e2ff',
          backgroundColor: 'grey',
          // backgroundColor: '#d2f8fd',
        },
        previousButtonContainer: {
          position: 'absolute',
          left: 20,
          // bottom: 10,
          zIndex: 1,
        },
        cameraButtonContainer: {
          position: 'absolute',
          left: 0,
          right: 0,
          bottom: 0,
          alignItems: 'center',
          zIndex: 0,
        },
      
        // New style for outer border container
        captureOuterBorder: {
          width: 80,
          height: 80,
          borderRadius: 44,
          justifyContent: 'center',
          alignItems: 'center',
          borderWidth: 2,
          borderColor: 'rgba(255, 255, 255, 0.4)', // More transparent white for outer border
          backgroundColor: 'transparent',
        },
      
        loadingContainer: {
          flex: 1,
          justifyContent: 'center',
          alignItems: 'center',
          backgroundColor: '#F5F5F5',
        },
        loadingText: {
          marginTop: 10,
          fontSize: 16,
          color: '#007AFF',
        },
        errorContainer: {
          flex: 1,
          justifyContent: 'center',
          alignItems: 'center',
          backgroundColor: '#F5F5F5',
          padding: 20,
        },
        errorText: {
          fontSize: 18,
          color: '#FF3B30',
          textAlign: 'center',
          marginBottom: 20,
        },
        retryButton: {
          backgroundColor: '#007AFF',
          paddingVertical: 12,
          paddingHorizontal: 24,
          borderRadius: 8,
        },
        retryButtonText: {
          color: '#FFF',
          fontSize: 16,
          fontWeight: '600',
        },
        preview: {
          flex: 1,
          marginVertical: 10,
          marginHorizontal: 10,
          borderRadius: 20,
          overflow: 'hidden',
          backgroundColor: '#000',
        },
        captureContainer: {
          position: 'absolute',
          bottom: 30,
          alignSelf: 'center',
        },
        modalBackground: {
          flex: 1,
          backgroundColor: 'rgba(0, 0, 0, 0.5)',
          justifyContent: 'flex-end',
        },
        modalWrapper: {
          backgroundColor: '#FFF',
          borderTopLeftRadius: 20,
          borderTopRightRadius: 20,
          // height: height * 0.8,
          padding: 20,
        },
        modalHeader: {
          fontSize: 24,
          fontWeight: 'bold',
          color: '#000',
          textAlign: 'center',
          marginBottom: 20,
        },
        wordCardsContainer: {
          marginBottom: 10,
        },
        wordCardsScroll: {
          paddingHorizontal: 10,
        },
        wordCard: {
          backgroundColor: '#F8F9FA',
          borderRadius: 12,
          padding: 15,
          marginRight: 15,
          marginVertical: 10,
          maxWidth: 250, // Set a reasonable max width
          alignSelf: 'flex-start', // Allow card size to adjust based on content
          shadowColor: '#000',
          shadowOffset: { width: 0, height: 2 },
          shadowOpacity: 0.1,
          shadowRadius: 4,
          elevation: 3,
          opacity: 1,
          // borderWidth:0.1,
          // borderColor:'#000',
          // marginLeft:5,
        },
        japaneseWord: {
          fontSize: 18,
          fontWeight: 'bold',
          color: '#000',
          marginBottom: 8,
          textAlign: 'center',
          flexWrap: 'wrap', // Wrap text within the container
        },
        romajiWord: {
          fontSize: 14,
          color: '#666',
          marginBottom: 4,
          textAlign: 'center',
          flexWrap: 'wrap', // Ensure no overflow
        },
        englishWord: {
          fontSize: 12,
          color: '#888',
          textAlign: 'center',
          marginBottom: 4,
          flexWrap: 'wrap', // Handle longer English words
        },
      
        translationsContainer: {
          flex: 1,
          marginBottom: 20,
        },
        translationsContent: {
          paddingBottom: 20,
        },
        translationSection: {
          backgroundColor: '#F8F9FA',
          borderRadius: 12,
          padding: 15,
          marginBottom: 15,
          opacity: 1,
        },
        sectionHeader: {
          flexDirection: 'row',
          justifyContent: 'space-between',
          alignItems: 'center',
          marginBottom: 10,
        },
        sectionSearchButton: {
          backgroundColor: '#007AFF',
          paddingVertical: 6,
          paddingHorizontal: 12,
          borderRadius: 8,
        },
        searchButtonText: {
          color: '#FFF',
          fontSize: 12,
          fontWeight: '600',
        },
      
        sectionTitle: {
          fontSize: 18,
          fontWeight: '600',
          color: '#000',
          marginBottom: 10,
        },
        translationText: {
          fontSize: 16,
          color: '#333',
          lineHeight: 24,
          opacity: 1,
        },
        closeButton: {
          backgroundColor: '#FF3B30',
          paddingVertical: 15,
          borderRadius: 12,
          alignItems: 'center',
        },
        closeButtonText: {
          color: '#FFF',
          fontSize: 16,
          fontWeight: '600',
        },
        loadingOverlay: {
          position: 'absolute',
          top: 0,
          left: 0,
          right: 0,
          bottom: 0,
          backgroundColor: 'rgba(0, 0, 0, 0.7)',
          justifyContent: 'center',
          alignItems: 'center',
          zIndex: 1000,
        },
      
        wordCardsScroll: {
          paddingHorizontal: 10,
        },
        // buttonsContainer: {
        //   position: 'absolute',
        //   bottom: 30,
        //   flexDirection: 'row',
        //   alignItems: 'center',
        //   justifyContent: 'center',
        //   width: '100%',
        //   paddingHorizontal: 20,
        //   gap: 20,
        // },
        capture: {
          backgroundColor: '#007AFF',
          width: 70,
          height: 70,
          borderRadius: 35,
          justifyContent: 'center',
          alignItems: 'center',
          shadowColor: '#000',
          shadowOffset: { width: 0, height: 2 },
          shadowOpacity: 0.25,
          shadowRadius: 4,
          elevation: 5,
          borderWidth: 2,
          borderColor: 'white',
        },
        previousButton: {
          // borderWidth: 1,
          // borderColor: 'white',
      
          backgroundColor: '#34C759',
          borderRadius: 25,
          padding: 12,
          flexDirection: 'row',
          alignItems: 'center',
          zIndex: 10,
          shadowColor: '#000',
          shadowOffset: { width: 0, height: 2 },
          shadowOpacity: 0.25,
          shadowRadius: 4,
          elevation: 5,
        },
        searchButtonsContainer: {
          flexDirection: 'row',
          justifyContent: 'space-between',
          marginTop: 10,
          paddingHorizontal: 5,
        },
        searchButton: {
          backgroundColor: '#007AFF',
          paddingVertical: 6,
          paddingHorizontal: 12,
          borderRadius: 8,
          marginHorizontal: 2,
        },
        searchButtonText: {
          color: '#FFF',
          fontSize: 12,
          fontWeight: '600',
        },
        webViewContainer: {
          flex: 1,
          backgroundColor: '#FFF',
        },
        webViewHeader: {
          height: 50,
          backgroundColor: '#F8F9FA',
          flexDirection: 'row',
          alignItems: 'center',
          justifyContent: 'flex-end',
          paddingHorizontal: 15,
          borderBottomWidth: 1,
          borderBottomColor: '#E5E5E5',
        },
        webViewCloseButton: {
          backgroundColor: '#FF3B30',
          paddingVertical: 8,
          paddingHorizontal: 15,
          borderRadius: 8,
        },
        webViewCloseButtonText: {
          color: '#FFF',
          fontSize: 14,
          fontWeight: '600',
        },
        webView: {
          flex: 1,
        },
        webViewLoading: {
          position: 'absolute',
          top: '50%',
          left: '50%',
          transform: [{ translateX: -25 }, { translateY: -25 }],
        },
});
